services:
    database:
        image: mongo:8.2
        ports:
            - "27017:27017"
        volumes:
            - ./mongo-data:/data/db

    app:
        build: ./backend
        ports:
            - "8080:8080"
        env_file:
            - ./backend/.env
        depends_on:
            - database

    worker:
        build: ./backend
        command: npm run worker
        env_file:
            - ./backend/.env
        depends_on:
            - database

    frontend:
        build:
            context: ./frontend
        ports:
            - "5173:5173"
        env_file:
            - ./frontend/.env
        depends_on:
            - app
        volumes:
            - ./frontend:/app
            - /app/node_modules